# Add 'Documentation' label to any file changes within 'docs' folder
Documentation:
    - changed-files:
          - any-glob-to-any-file: docs/*

# Add 'release' label to any PR that is opened against the `main` branch
automerge:
    - base-branch: "main"
