// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

    documentationSidebar: [
        {
            type: "category",
            label: "Getting Started",
            items: ["intro"],
        },
        {
            type: "category",
            label: "Audio Team",
            link: {
                type: "generated-index",
                description:
                    "Panduan teknis untuk mengelola sistem audio gereja, termasuk pengaturan mixer, penggunaan mikrofon, dan standar kualitas suara. Sangat penting untuk menjaga kenyamanan jemaat dalam mendengar.",
            },
            items: [
                {
                    type: "autogenerated",
                    dirName: "audio",
                },
            ],
        },
        {
            type: "category",
            label: "Video Team",
            link: {
                type: "generated-index",
                description:
                    "Dokumentasi ini mencakup pengaturan kamera, pencahayaan, dan prosedur live streaming. Cocok untuk tim yang bertugas menangkap momen ibadah untuk keperluan dokumentasi atau siaran langsung.",
            },
            items: [
                {
                    type: "autogenerated",
                    dirName: "video",
                },
            ],
        },
        {
            type: "category",
            label: "Slides & Presentation",
            link: {
                type: "generated-index",
                description:
                    "Bagian ini membahas penggunaan software presentasi seperti EasyWorship atau PowerPoint, serta pengelolaan lirik, ayat Alkitab, dan media visual lainnya untuk tampilan proyektor saat ibadah.",
            },
            items: [
                {
                    type: "autogenerated",
                    dirName: "slides",
                },
            ],
        },
        {
            type: "category",
            label: "Inventory & Tools",
            link: {
                type: "generated-index",
                description:
                    "Berisi daftar peralatan multimedia yang dimiliki gereja serta panduan perawatan dan jadwal pengecekan. Berguna untuk menjaga perlengkapan tetap dalam kondisi optimal dan tertata.",
            },
            items: [
                {
                    type: "autogenerated",
                    dirName: "inventory",
                },
            ],
        },
        {
            type: "category",
            label: "Training & Resources",
            link: {
                type: "generated-index",
                description:
                    "Kumpulan materi pelatihan, tautan video tutorial, dan dokumen pendukung lainnya untuk membantu anggota tim memahami tugas dan tanggung jawab mereka lebih baik.",
            },
            items: [
                {
                    type: "autogenerated",
                    dirName: "training",
                },
            ],
        },
        {
            type: "category",
            label: "Miscellaneous",
            link: {
                type: "generated-index",
                description:
                    "Kategori ini berisi hal-hal tambahan yang mendukung pelayanan Multimedia.",
            },
            items: [
                {
                    type: "autogenerated",
                    dirName: "misc",
                },
            ],
        },
        {
            type: "category",
            label: "Troubleshooting & FAQ",
            link: {
                type: "generated-index",
                description:
                    "Solusi cepat untuk masalah umum yang sering terjadi di bidang audio, video, dan presentasi. Juga termasuk FAQ dan checklist darurat untuk kondisi teknis saat ibadah berlangsung.",
            },
            items: [
                {
                    type: "autogenerated",
                    dirName: "troubleshooting",
                },
            ],
        },
        {
            type: "category",
            label: "Docusaurus",
            items: [
                {
                    type: "autogenerated",
                    dirName: "docusaurus",
                },
            ],
        },
    ],

    // But you can create a sidebar manually
    /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
