backend:
    name: github
    branch: main
    repo: "erdav544/gmt-docs"
    base_url: https://decap-proxy.erdav.eu.org

local_backend: true

locale: en

# These lines should *not* be indented
media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/" # The src attribute for uploaded media will begin with /images/uploads

slug:
    encoding: "ascii"
    clean_accents: true
    sanitize_replacement: "_"

collections:
    - name: docs
      label: "Docs"
      label_singular: "Doc"
      folder: docs
      # adding a nested object will show the collection folder structure
      nested:
          depth: 4 # max depth to show in the collection tree
          summary: "{{title}}" # optional summary for a tree node, defaults to the inferred title field
      identifier_field: title
      extension: md
      format: frontmatter
      widget: "list"
      create: true
      sortableFields: ["title", "sidebar_position"]
      fields:
          - label: "Sidebar position"
            name: "sidebar_position"
            widget: "number"
            required: false
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "text"
          - label: "Image"
            name: "image"
            widget: "image"
            allow_multiple: false
            required: false
          - label: "Body"
            name: "body"
            widget: "markdown"
